Repository ConceptBe/conceptbe-backend, pull requests merged in 2024-02, with the labels that each got.

#25 feat: 마이 프로필 조회 기능 구현
  src/main/java/kr/co/conceptbe/bookmark/repository/BookmarkRepository.java
  src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
  src/main/java/kr/co/conceptbe/idea/domain/persistence/IdeaRepository.java
  src/main/java/kr/co/conceptbe/member/application/MemberService.java
  src/main/java/kr/co/conceptbe/member/application/dto/MemberIdeaResponse.java
  src/main/java/kr/co/conceptbe/member/controller/MemberController.java
Labels: feat

#29 refactor: 닉네임 중복 확인 api 반환 값 변경
  src/main/java/kr/co/conceptbe/member/application/MemberService.java
  src/main/java/kr/co/conceptbe/member/controller/MemberController.java
Labels: refactor

#32 refactor: 마이페이지 내 프로필, 아이디어들 컬럼 추가
  src/main/java/kr/co/conceptbe/member/application/MemberService.java
  src/main/java/kr/co/conceptbe/member/application/dto/GetMemberProfileResponse.java
  src/main/java/kr/co/conceptbe/member/application/dto/MemberIdeaResponse.java
  src/main/java/kr/co/conceptbe/member/application/dto/MemberIdeaResponseOption.java
  src/main/java/kr/co/conceptbe/member/controller/MemberController.java
  src/main/java/kr/co/conceptbe/member/controller/doc/MemberApi.java
Labels: refactor

#34 [feat] TeamRecruitment 테이블 삭제, 필터링 기능 도입 (스웨거)
  .gitignore
  build.gradle
  src/main/java/kr/co/conceptbe/common/config/QueryDSLConfig.java
  src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
  src/main/java/kr/co/conceptbe/idea/application/request/FilteringRequest.java
  src/main/java/kr/co/conceptbe/idea/application/request/IdeaRequest.java
  src/main/java/kr/co/conceptbe/idea/application/response/BestIdeaResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/BranchResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/FindIdeaWriteResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/IdeaResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/RegionResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/SkillCategoryResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/SkillResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/TeamRecruitmentCategoryResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/TeamRecruitmentResponse.java
  src/main/java/kr/co/conceptbe/idea/domain/Idea.java
  src/main/java/kr/co/conceptbe/idea/domain/IdeaSkillCategory.java
  src/main/java/kr/co/conceptbe/idea/domain/persistence/IdeaRepository.java
  src/main/java/kr/co/conceptbe/idea/domain/persistence/IdeaRepositoryCustom.java
  src/main/java/kr/co/conceptbe/idea/domain/persistence/IdeaRepositoryCustomImpl.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaSkillCategories.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaTeamRecruitments.java
  src/main/java/kr/co/conceptbe/idea/dto/IdeaDetailResponse.java
  src/main/java/kr/co/conceptbe/idea/presentation/IdeaController.java
  src/main/java/kr/co/conceptbe/idea/presentation/doc/IdeaApi.java
  src/main/java/kr/co/conceptbe/member/application/dto/MemberIdeaResponse.java
  src/main/java/kr/co/conceptbe/skill/domain/SkillCategory.java
  src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
  src/main/java/kr/co/conceptbe/teamrecruitment/domain/TeamRecruitment.java
  src/main/java/kr/co/conceptbe/teamrecruitment/domain/TeamRecruitmentCategory.java
  src/main/java/kr/co/conceptbe/teamrecruitment/domain/persistence/TeamRecruitmentCategoryRepository.java
  src/main/java/kr/co/conceptbe/teamrecruitment/domain/persistence/TeamRecruitmentRepository.java
  src/main/java/kr/co/conceptbe/teamrecruitment/exception/NotFoundTeamRecruitmentCategoryException.java
  src/main/java/kr/co/conceptbe/teamrecruitment/exception/NotFoundTeamRecruitmentException.java
  src/main/resources/application.yml
  src/test/java/kr/co/conceptbe/idea/fixture/IdeaFixture.java
  src/test/java/kr/co/conceptbe/idea/persistence/IdeaRepositoryTest.java
Labels: documentation, feat, refactor
