Repository ConceptBe/conceptbe-backend, pull requests merged in 2024-03, with the labels that each got.

#44 [hotfix] writing API 잘못된 응답 수정
  src/main/java/kr/co/conceptbe/idea/application/response/SkillCategoryResponse.java
  src/main/java/kr/co/conceptbe/skill/domain/SkillCategory.java
  src/test/java/kr/co/conceptbe/idea/application/IdeaServiceTest.java
Labels: hotfix

#45 [feat] 게시글 수정 기능 개발
  src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
  src/main/java/kr/co/conceptbe/idea/application/request/IdeaUpdateRequest.java
  src/main/java/kr/co/conceptbe/idea/domain/Idea.java
  src/main/java/kr/co/conceptbe/idea/domain/persistence/IdeaRepositoryCustomImpl.java
  src/main/java/kr/co/conceptbe/idea/dto/IdeaDetailResponse.java
  src/main/java/kr/co/conceptbe/idea/presentation/IdeaController.java
  src/main/java/kr/co/conceptbe/idea/presentation/doc/IdeaApi.java
  src/main/java/kr/co/conceptbe/member/domain/Member.java
  src/test/java/kr/co/conceptbe/idea/application/IdeaServiceTest.java
  src/test/java/kr/co/conceptbe/idea/fixture/IdeaFixture.java
  src/test/java/kr/co/conceptbe/idea/persistence/IdeaRepositoryTest.java
  src/test/java/kr/co/conceptbe/member/fixture/MemberFixture.java
Labels: feat

#46 fix: 프로필 조회시 스킬 레벨도 같이 반환하도록 수정
  src/main/java/kr/co/conceptbe/member/application/MemberService.java
  src/main/java/kr/co/conceptbe/member/application/dto/GetMemberProfileResponse.java
  src/main/java/kr/co/conceptbe/member/application/dto/MemberProfileSkillResponse.java
Labels: fix

#50 [hotfix] 피드 전체 조회 id 필드 누락
  src/main/java/kr/co/conceptbe/idea/application/response/MemberResponse.java
Labels: hotfix

#54 스킬 중복선택 방지 추가
  src/main/java/kr/co/conceptbe/auth/application/OauthService.java
  src/main/java/kr/co/conceptbe/auth/application/dto/SignUpRequest.java
  src/main/java/kr/co/conceptbe/auth/application/dto/SkillRequest.java
  src/main/java/kr/co/conceptbe/auth/application/dto/SkillRequests.java
  src/main/java/kr/co/conceptbe/auth/application/dto/UpdateMemberProfileRequest.java
  src/main/java/kr/co/conceptbe/skill/exception/DuplicatedSkillCategoryException.java
  src/test/java/kr/co/conceptbe/auth/application/OauthServiceTest.java
  src/test/java/kr/co/conceptbe/auth/fixture/AuthFixture.java
Labels: bug

#59 [hotfix] 게시글 목록 조회시 VO 로 인한 예외 발생 해결
  src/main/java/kr/co/conceptbe/idea/application/request/FilteringRequest.java
  src/main/java/kr/co/conceptbe/idea/domain/persistence/IdeaRepositoryCustomImpl.java
  src/main/java/kr/co/conceptbe/idea/presentation/IdeaController.java
  src/test/java/kr/co/conceptbe/idea/persistence/IdeaRepositoryTest.java
Labels: hotfix

#61 [refactor] 외래키로 인한 게시글 삭제 불가를 해결한다.
  src/main/java/kr/co/conceptbe/bookmark/Bookmark.java
  src/main/java/kr/co/conceptbe/comment/Comment.java
  src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
  src/main/java/kr/co/conceptbe/idea/domain/Hit.java
  src/main/java/kr/co/conceptbe/idea/domain/Idea.java
  src/main/java/kr/co/conceptbe/idea/domain/IdeaLike.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaBranches.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaPurposes.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaSkillCategories.java
  src/test/java/kr/co/conceptbe/idea/application/IdeaServiceTest.java
Labels: refactor

#63 [refactor] 게시글 수정시 동일한 항목이 여러개 생기는 것을 수정한다.
  src/main/java/kr/co/conceptbe/idea/domain/Idea.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaBranches.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaPurposes.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaSkillCategories.java
  src/test/java/kr/co/conceptbe/idea/application/IdeaServiceTest.java
Labels: refactor
