Repository ConceptBe/conceptbe-backend, pull requests merged in 2024-01, with the labels that each got.

#8 feat: Auth Interceptor, resolver 추가
  src/main/java/kr/co/conceptbe/auth/config/AuthConfig.java
  src/main/java/kr/co/conceptbe/auth/exception/TokenMissingException.java
  src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
  src/main/java/kr/co/conceptbe/auth/presentation/MandatoryJwtArgumentResolver.java
  src/main/java/kr/co/conceptbe/auth/presentation/OptionalJwtArgumentResolver.java
  src/main/java/kr/co/conceptbe/auth/presentation/dto/AuthCredentials.java
  src/main/java/kr/co/conceptbe/auth/support/BearerTokenExtractor.java
  src/main/java/kr/co/conceptbe/common/auth/Auth.java
  src/main/java/kr/co/conceptbe/common/auth/OptionalAuth.java
Labels: feat

#10 feat: 회원가입 Validation 추가
  build.gradle
  src/main/java/kr/co/conceptbe/common/exception/GlobalExceptionHandler.java
  src/main/java/kr/co/conceptbe/member/MemberRepository.java
  src/main/java/kr/co/conceptbe/member/application/MemberService.java
  src/main/java/kr/co/conceptbe/member/application/dto/SignUpRequest.java
  src/main/java/kr/co/conceptbe/member/controller/MemberController.java
  src/main/java/kr/co/conceptbe/member/exception/AlreadyExistsNicknameException.java
Labels: feat

#12 feat: 회원가입 초기 정보 조회 기능 추가
  src/main/java/kr/co/conceptbe/common/exception/GlobalExceptionHandler.java
  src/main/java/kr/co/conceptbe/member/application/MemberService.java
  src/main/java/kr/co/conceptbe/member/application/dto/DetailSkillResponse.java
  src/main/java/kr/co/conceptbe/member/application/dto/FindSignUpResponse.java
  src/main/java/kr/co/conceptbe/member/application/dto/MainSkillResponse.java
  src/main/java/kr/co/conceptbe/member/application/dto/PurposeResponse.java
  src/main/java/kr/co/conceptbe/member/controller/MemberController.java
  src/main/java/kr/co/conceptbe/skill/application/SkillService.java
  src/main/java/kr/co/conceptbe/skill/application/dto/FindDetailSkillResponse.java
  src/main/java/kr/co/conceptbe/skill/application/dto/FindMainSkillResponse.java
  src/main/java/kr/co/conceptbe/skill/presentation/SkillController.java
  src/test/java/kr/co/conceptbe/skill/application/SkillServiceTest.java
Labels: feat

#13 refactor: 패키지 변경
  src/main/java/kr/co/conceptbe/auth/application/OauthService.java
  src/main/java/kr/co/conceptbe/auth/application/dto/DetailSkillResponse.java
  src/main/java/kr/co/conceptbe/auth/application/dto/FindSignUpResponse.java
  src/main/java/kr/co/conceptbe/auth/application/dto/MainSkillResponse.java
  src/main/java/kr/co/conceptbe/auth/application/dto/PurposeResponse.java
  src/main/java/kr/co/conceptbe/auth/application/dto/SignUpRequest.java
  src/main/java/kr/co/conceptbe/auth/application/dto/SignUpSkillRequest.java
  src/main/java/kr/co/conceptbe/auth/domain/authcode/AuthCodeRequestUrlProvider.java
  src/main/java/kr/co/conceptbe/auth/domain/authcode/AuthCodeRequestUrlProviderHandler.java
  src/main/java/kr/co/conceptbe/auth/domain/client/OauthMemberClient.java
  src/main/java/kr/co/conceptbe/auth/domain/client/OauthMemberClientHandler.java
  src/main/java/kr/co/conceptbe/auth/infra/oauth/dto/OauthMemberInformation.java
  src/main/java/kr/co/conceptbe/auth/infra/oauth/kakao/authcode/KakaoAuthCodeRequestUrlProvider.java
  src/main/java/kr/co/conceptbe/auth/infra/oauth/kakao/client/KakaoMemberClient.java
  src/main/java/kr/co/conceptbe/auth/presentation/OauthController.java
  src/main/java/kr/co/conceptbe/auth/presentation/OauthServerTypeConverter.java
  src/main/java/kr/co/conceptbe/bookmark/Bookmark.java
  src/main/java/kr/co/conceptbe/bookmark/service/BookmarkService.java
  src/main/java/kr/co/conceptbe/comment/Comment.java
  src/main/java/kr/co/conceptbe/comment/CommentLike.java
  src/main/java/kr/co/conceptbe/comment/service/CommentService.java
  src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
  src/main/java/kr/co/conceptbe/idea/domain/Hit.java
  src/main/java/kr/co/conceptbe/idea/domain/Idea.java
  src/main/java/kr/co/conceptbe/idea/domain/IdeaLike.java
  src/main/java/kr/co/conceptbe/idea/domain/persistence/IdeaRepository.java
  src/main/java/kr/co/conceptbe/idea/presentation/IdeaController.java
  src/main/java/kr/co/conceptbe/idea/presentation/dto/response/MemberResponse.java
  src/main/java/kr/co/conceptbe/member/application/MemberService.java
  src/main/java/kr/co/conceptbe/member/controller/MemberController.java
  src/main/java/kr/co/conceptbe/member/domain/Member.java
  src/main/java/kr/co/conceptbe/member/domain/MemberBranch.java
  src/main/java/kr/co/conceptbe/member/domain/MemberPurpose.java
  src/main/java/kr/co/conceptbe/member/domain/MemberSkillCategory.java
  src/main/java/kr/co/conceptbe/member/domain/OauthId.java
  src/main/java/kr/co/conceptbe/member/domain/OauthServerType.java
  src/main/java/kr/co/conceptbe/member/domain/Region.java
  src/main/java/kr/co/conceptbe/member/persistence/MemberRepository.java
  src/test/java/kr/co/conceptbe/auth/application/OauthServiceTest.java
  src/test/java/kr/co/conceptbe/auth/fixture/AuthFixture.java
Labels: refactor

#15 feat: 게시글 작성, 최근 게시글, 인기 게시글 조회 기능 보완
  src/main/java/kr/co/conceptbe/auth/application/OauthService.java
  src/main/java/kr/co/conceptbe/auth/application/dto/PurposeResponse.java
  src/main/java/kr/co/conceptbe/branch/domain/Branch.java
  src/main/java/kr/co/conceptbe/branch/domain/persistense/BranchRepository.java
  src/main/java/kr/co/conceptbe/branch/exception/NotFoundBranchException.java
  src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
  src/main/java/kr/co/conceptbe/idea/application/request/IdeaRequest.java
  src/main/java/kr/co/conceptbe/idea/application/response/BestIdeaResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/BranchResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/FindIdeaWriteResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/IdeaResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/MemberResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/RegionResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/TeamRecruitmentCategoryResponse.java
  src/main/java/kr/co/conceptbe/idea/application/response/TeamRecruitmentResponse.java
  src/main/java/kr/co/conceptbe/idea/domain/Idea.java
  src/main/java/kr/co/conceptbe/idea/domain/IdeaBranch.java
  src/main/java/kr/co/conceptbe/idea/domain/IdeaTeamRecruitment.java
  src/main/java/kr/co/conceptbe/idea/domain/persistence/IdeaRepository.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/CooperationWay.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaBranches.java
  src/main/java/kr/co/conceptbe/idea/domain/vo/IdeaTeamRecruitments.java
  src/main/java/kr/co/conceptbe/idea/dto/IdeaDetailResponse.java
  src/main/java/kr/co/conceptbe/idea/exception/NotFoundCooperationWayException.java
  src/main/java/kr/co/conceptbe/idea/presentation/IdeaController.java
  src/main/java/kr/co/conceptbe/member/domain/MemberBranch.java
  src/main/java/kr/co/conceptbe/member/exception/UnAuthorizedMemberException.java
  src/main/java/kr/co/conceptbe/purpose/domain/persistence/PurposeRepository.java
  src/main/java/kr/co/conceptbe/region/domain/Region.java
  src/main/java/kr/co/conceptbe/region/domain/RegionName.java
  src/main/java/kr/co/conceptbe/region/domain/presentation/RegionRepository.java
  src/main/java/kr/co/conceptbe/region/exception/NotFoundRegionNameException.java
  src/main/java/kr/co/conceptbe/teamrecruitment/domain/TeamRecruitment.java
  src/main/java/kr/co/conceptbe/teamrecruitment/domain/TeamRecruitmentCategory.java
  src/main/java/kr/co/conceptbe/teamrecruitment/domain/persistence/TeamRecruitmentCategoryRepository.java
  src/main/java/kr/co/conceptbe/teamrecruitment/domain/persistence/TeamRecruitmentRepository.java
  src/main/java/kr/co/conceptbe/teamrecruitment/exception/NotFoundTeamRecruitmentCategoryException.java
  src/main/java/kr/co/conceptbe/teamrecruitment/exception/NotFoundTeamRecruitmentException.java
  src/test/java/kr/co/conceptbe/auth/application/OauthServiceTest.java
Labels: feat

#17 feat: 로그인 시 간단 정보 추가 및 My page 프로필 정보 조회 API 추가
  src/main/java/kr/co/conceptbe/auth/application/OauthService.java
  src/main/java/kr/co/conceptbe/auth/application/dto/AuthMemberInformation.java
  src/main/java/kr/co/conceptbe/auth/application/dto/AuthResponse.java
  src/main/java/kr/co/conceptbe/auth/presentation/OauthController.java
  src/main/java/kr/co/conceptbe/member/application/MemberService.java
  src/main/java/kr/co/conceptbe/member/application/dto/GetMemberProfileResponse.java
  src/main/java/kr/co/conceptbe/member/controller/MemberController.java
  src/main/java/kr/co/conceptbe/member/domain/Member.java
  src/test/java/kr/co/conceptbe/auth/application/OauthServiceTest.java
Labels: feat

#20 [hotfix] IdeaResponse 에 ID 추가
  src/main/java/kr/co/conceptbe/idea/application/response/IdeaResponse.java
Labels: bug
